name: qopenhd

on: [push]

jobs:
  pi-stretch:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo tune2fs -O "^dir_index" /dev/sda1
        sudo docker run --privileged linuxkit/binfmt:v0.6
        sudo apt -y update
        sudo apt -y install qemu-user-static
    - name: build
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      run: |
         export DOCKERFILE=Dockerfile-pi-stretch
         docker build -f $DOCKERFILE --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .
  pi-buster:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo tune2fs -O "^dir_index" /dev/sda1
        sudo docker run --privileged linuxkit/binfmt:v0.6
        sudo apt -y update
        sudo apt -y install qemu-user-static
    - name: build
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      run: |
         export DOCKERFILE=Dockerfile-pi-buster
         docker build -f $DOCKERFILE --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .




